title: QED
email: hi@chenna.me
description: >- # this means to ignore newlines until "baseurl:"
  Personal URL Shortener
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kautilyach
github_username:  hashb

# Build settings
theme: no-style-please
plugins:
  - jekyll-feed

# URL Shortener Configuration
collections:
  redirects:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "redirects"
    values:
      layout: "post"


prose:
  rooturl: '_redirects'
  siteurl: 'https://qed.bz/'
  media: 'assets/uploads'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /_sass
  metadata:
    _redirects:
      - name: "title"
        field:
          element: "text"
          value: "Redirecting..."
      - name: "redirect_url"
        field:
          element: "text"
          label: "Link"
          value: ""
